version: '3.1'
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=5
      - PMA_HOST="<ENTER YOUR DATBASE HOSTNAME>"
